name: Deploy Examples

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  astro:
    name: Deploy Astro
    defaults:
      run:
        working-directory: with-astro
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Astro
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: examples-deno-astro
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: with-astro/public


  eleventy:
    name: Deploy Eleventy
    defaults:
      run:
        working-directory: with-eleventy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: examples-deno-eleventy
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: with-eleventy/_site


  hugo:
    name: Deploy Hugo
    defaults:
      run:
        working-directory: with-hugo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: examples-deno-hugo
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: with-hugo/public


  jekyll:
    name: Deploy Jekyll
    defaults:
      run:
        working-directory: with-jekyll
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: gha-utilities/jekyll-build@v0.0.8
        with:
          source: with-jekyll
          destination: _site

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: examples-deno-jekyll
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: with-jekyll/_site

